In [8]:
import cv2
import numpy

In [2]:
# https://github.com/pypa/pipenv/issues/1313

In [4]:
image = cv2.imread("images/smallgray.png", 0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
cv2.imwrite("images/newsmallgray.png", image)

True

In [11]:
m = numpy.asarray(image)
m

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
type(image)

numpy.ndarray

In [14]:
image[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
image.shape

(3, 5)

In [17]:
image[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [18]:
image[2,4]

182

In [20]:
for i in image:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [21]:
for i in image.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [22]:
for i in image.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
for i in image.T.flat:
    print(i)

187
198
209
158
125
134
104
255
255
121
255
97
143
147
182


In [27]:
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
ims = numpy.hstack((image, image))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
ims = numpy.vstack((image, image))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [30]:
lst = numpy.hsplit(image, 5)
lst

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [32]:
lst = numpy.vsplit(ims, 3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [33]:
type(lst)

list

In [34]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)